### PR TITLE
update NPM packages to the latest

### PR DESCRIPTION
**Pull request by ChunxiAlexLuo**
Signed-off-by: Chunxi Luo chuluo@redhat.com

### CODE REVIEW

**Comment by ChunxiAlexLuo** [comment]
the only un-updated package are helmet/monaco-editor-webpack-plugin/react-monaco-editor, which will break UI

react/react-dom 17 works fine, but wait for a newer enzyme to support react 17

**Review by willkutler — APPROVED** [review]

**Comment by ChunxiAlexLuo** [comment]
If you are using webpack v5 or above you do not need to install this plugin. Webpack v5 comes with the latest terser-webpack-plugin out of the box.

https://www.npmjs.com/package/terser-webpack-plugin

**Comment by ChunxiAlexLuo** [comment]
Screen Shot 2021-06-01 at 1 06 39 PM

**Comment by ChunxiAlexLuo** [comment]
https://jestjs.io/blog/2021/05/25/jest-27

Running tests in a JSDOM environment incurs a significant performance overhead. Because this was the default behavior of Jest unless otherwise configured up until now, users who are writing Node apps, for example, may not even know they are given an expensive DOM environment that they do not even need.
For this reason, we are changing the default test environment from "jsdom" to "node". If you are affected by this change because you use DOM APIs and do not have the test environment explicitly configured, you should be receiving an error when e.g. document is accessed, and you can configure "testEnvironment": "jsdom" or use per-file environment configuration to resolve this.

**Pull request merged**
