### PR TITLE
Prompt user to install Ansible Operator in modal

### PR DESCRIPTION
**Pull request by JustinKuli**
Ansible automations require the ansible operator to be installed in, but
we currently don't check that before allowing the UI to try to create a
Job. This will create an Alert at the top of the ansible automation
modal if the operator is not installed, linking the user to the
OperatorHub where they could install it. It also removes the "Save" and
"Cancel" buttons if the operator is not installed.

Refs:
 - https://github.com/open-cluster-management/backlog/issues/12826

Signed-off-by: Justin Kulikauskas <jkulikau@redhat.com>

Requires https://github.com/open-cluster-management/grc-ui-api/pull/139.

### CODE REVIEW

**Comment by JustinKuli** [comment]
Here's what the alert looks like:
Screen Shot 2021-06-15 at 5 01 10 PM

This alert would be above any alerts from queries for the rest of the modal (for example if the credentials couldn't be loaded).

**Review by ChunxiAlexLuo — APPROVED** [review]
/lgtm

**Comment by ChunxiAlexLuo** [comment]
need some unit test cases

**Pull request merged**
