### PR TITLE
Use patternfly text components to render welcome page text

### PR DESCRIPTION
**Pull request by zlayne**
Signed-off-by: Zack Layne <zlayne@redhat.com>

Related Issue: https://github.com/open-cluster-management/backlog/issues/14569

### CODE REVIEW

**Comment by KevinFCormier** [comment]
The headings on the cards still seem to be using RedHatText instead of RedHatDisplay

image

**Comment by zlayne** [comment]
@KevinFCormier This is the title text using RedHatDisplay, which seems to be more bold than the design given.
Screen Shot 2021-09-30 at 10 00 20 AM

**Pull request merged**
