### PR TITLE
Use common ui-components

### PR DESCRIPTION
**Pull request by JustinKuli**
Replaces many instances of the grc PatternFlyTable implementation with AcmTable, and uses AcmDescriptionList. For https://github.com/open-cluster-management/backlog/issues/12036

@ycao56 / other reviewers: if it helps, I can collect screenshots of before/after to help verify the changes. I wasn't really sure what the procedure was around updating the test snapshots.

### CODE REVIEW

**Comment by ycao56** [comment]
image
The section title styling no longer matches. Can you open an issue to address it in a separate pr?

**Comment by ycao56** [comment]
The search value is shared across multiple tables on the same page
image

**Comment by JustinKuli** [comment]
Opened https://github.com/open-cluster-management/backlog/issues/12362 for the title styling.

Good eye on the search bars, I'll work on that.

**Comment by JustinKuli** [comment]
Updated search functions on the template tables (by removing them - the default AcmTable search works fine for those since they don't use any data from the URL params).

**Comment by ycao56** [comment]
Can you use regular expression to check both labels?

**Comment by ycao56** [comment]
https://github.com/open-cluster-management/grc-ui/pull/606 has what you need. needs to coordinate the merge of both prs to make the e2e working.

**Review by ycao56 — APPROVED** [review]

**Pull request merged**
