### PR TITLE
Delete policy should also delete its policy automation

### PR DESCRIPTION
**Pull request by ChunxiAlexLuo**
Signed-off-by: Chunxi Luo chuluo@redhat.com

https://github.com/open-cluster-management/backlog/issues/14036

e2e test will be added in https://github.com/open-cluster-management/backlog/issues/14037 for both https://github.com/open-cluster-management/backlog/issues/13746 and https://github.com/open-cluster-management/backlog/issues/14036

### CODE REVIEW

**Comment by ChunxiAlexLuo** [comment]
before

Screen Shot 2021-08-11 at 9 24 32 AM

**Comment by ChunxiAlexLuo** [comment]
after

Screen Shot 2021-08-11 at 9 24 46 AM

**Review by KevinFCormier — APPROVED** [review]
Looks good!

**Pull request merged**
