### PR TITLE
Update to ui-components 1.25.2

### PR DESCRIPTION
**Pull request by KevinFCormier**
https://github.com/open-cluster-management/backlog/issues/18158
Signed-off-by: Kevin Cormier <kcormier@redhat.com>

### CODE REVIEW

**Comment by smithbw88** [comment]
Waiting on these PRs to include in 2.4.1 RC2.  Please resolve ASAP.

**Comment by KevinFCormier** [comment]
After temporary issue with build system not being able to resolve github.com, next attempt failed with an intermittent detached DOM element issue. Happens regularly in canaries, but first time I have seen it happen on Prow. Trying another run.

**Pull request merged**
