### PR TITLE
[release-2.1] fix hardcode namespace in 2.1 branch

### PR DESCRIPTION
**Pull request by yahliu**
Signed-off-by: yahliu <yahliu@redhat.com>

### CODE REVIEW

**Comment by dhaiducek** [comment]
For consistency between releases, would it be okay for us to close this PR and I'll cherry-pick when the change was originally made (https://github.com/open-cluster-management/grc-ui/pull/577) down to this release? Is this a change that also needs to be in `2.2`?

**Comment by dhaiducek** [comment]
Ah, especially since `2.2` and `2.1` can't accept PRs from external forks since the builds are in Travis and not Prow. I'll do the cherry-pick now and close this PR.

**Comment by dhaiducek** [comment]
Sorry--I wasn't thinking. The cherry-picks conflict because of the move to Cypress. 🤦  Reopening and approving. 🙂

**Review by dhaiducek — APPROVED** [review]

**Comment by hchenxa** [comment]
The build failed due to 
```
$ npm ci 
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/open-cluster-management/react-d3-radar.git
npm ERR! 
npm ERR! Warning: Permanently added the RSA host key for IP address '140.82.114.4' to the list of known hosts.
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2021-06-15T03_02_39_590Z-debug.log
```
@dhaiducek, could u help to take a look?

**Comment by hchenxa** [comment]
seems the build failed due to the fork repo, may need to re-create the PR for 2.1  branch.

**Comment by yahliu** [comment]
@dhaiducek  I already applied request to join the team. Can you or someone approve it ? or you can help to make the PR for this change ?

**Comment by dhaiducek** [comment]
Sorry, I hadn’t merged it because I was thinking there was a code freeze, but that’s for 2.2. Merging now.

**Pull request merged**
