### PR TITLE
Ansible Modal Stylish and polish

### PR DESCRIPTION
**Pull request by ChunxiAlexLuo**
https://github.com/open-cluster-management/backlog/issues/12838

The only un-fixed stylish issue is 7th - `Extra variables styling is different. Use Clipboard copy - Expanded PF component`
There are some issues to use MonacoEditor inside Clipboard, which will be fixed in a separate pr later.

https://github.com/open-cluster-management/backlog/issues/13079

Also fixed Ansible Modal console log error

### CODE REVIEW

**Comment by ChunxiAlexLuo** [comment]
Screen Shot 2021-06-09 at 11 48 41 AM
Screen Shot 2021-06-09 at 11 49 07 AM

**Comment by JustinKuli** [comment]
A couple of nitpicks:

For item 3 in the issue, it says "Red Hat Text Medium 14px". In my browser I see it resolved to 16px font-size. The spacing is good, and it looks good, so I don't know if it needs to change, I just wanted to mention it.

For item 5, the tabs aren't quite the full width. Actually, when mousing over History, it's tab doesn't even go as far as some of the content below it:
Screen Shot 2021-06-09 at 1 05 16 PM

Again, I don't know how strict we need to be with the change, so this might not need to be adjusted.

**Review by JustinKuli — APPROVED** [review]
/lgtm

Thanks for updates :)

**Pull request merged**
