### PR TITLE
Update the Cluster Violation Messages for Governance #13612

### PR DESCRIPTION
**Pull request by ChunxiAlexLuo**
Signed-off-by: Chunxi Luo chuluo@redhat.com

This pr fixed the below issues:

https://github.com/open-cluster-management/backlog/issues/13612

https://github.com/open-cluster-management/backlog/issues/13707

https://github.com/open-cluster-management/backlog/issues/13485

### CODE REVIEW

**Comment by ChunxiAlexLuo** [comment]
Screen Shot 2021-07-01 at 2 54 39 PM

**Comment by JustinKuli** [comment]
@ChunxiAlexLuo, does this cover https://github.com/open-cluster-management/backlog/issues/13485? I couldn't test adding an automation quickly, but I didn't notice anything that would have fixed that refresh on other pages (I might have just missed it).

The rest looks good

**Comment by ChunxiAlexLuo** [comment]
> @ChunxiAlexLuo, does this cover [open-cluster-management/backlog#13485](https://github.com/open-cluster-management/backlog/issues/13485)? I couldn't test adding an automation quickly, but I didn't notice anything that would have fixed that refresh on other pages (I might have just missed it).
> 
> The rest looks good

Sorry for misleading, https://github.com/open-cluster-management/backlog/issues/13485 should has been fixed in https://github.com/open-cluster-management/grc-ui/pull/661

**Review by JustinKuli — APPROVED** [review]
/lgtm

**Pull request merged**
