### PR TITLE
 Error message reported but then disappeared when users swtich between…

### PR DESCRIPTION
**Pull request by ChunxiAlexLuo**
https://github.com/open-cluster-management/backlog/issues/13797

Signed-off-by: Chunxi Luo chuluo@redhat.com

### CODE REVIEW

**Comment by ChunxiAlexLuo** [comment]
The error msg should only appear when non-loading and no-query-result  status

**Review by willkutler — APPROVED** [review]

**Comment by dhaiducek** [comment]
/hold

(for `2.4` to open)

**Comment by ChunxiAlexLuo** [comment]
/hold

hold for 2.4

**Pull request merged**
