### PR TITLE
Patch cluster with `latest-<version>`

### PR DESCRIPTION
**Pull request by dhaiducek**
Has a dependency on:
- #733

### CODE REVIEW

**Comment by dhaiducek** [comment]
/hold for reviews

Since Framework gates images, this PR patches the E2E cluster with the `latest` GRC images (just like we already do with the API) so that we don't have to force-merge PRs when component messages or the like change when the images are held back by the Framework.

FYI @KevinFCormier

**Review by mprahl — APPROVED** [review]

**Pull request merged**
